(ns parsimony.example-projects.demo)

(def demo-partial-string
  "{\"~:id\":null,\"~:last-saved\":1499468081251,\"~:description\":\"DEMO-PARTIAL\",\"~:sources\":{\"~i1\":{\"~:string\":\"expr = ID ;\\nexpr = NUM ;\\nexpr = LPAREN expr RPAREN ;\\nexpr = expr EXP expr {right} ;\\nexpr = expr PLUS expr {left} ;\\nexpr = expr TIMES expr {left} ;\\n\\n-array-inner = expr ;\\n-array-inner = expr COMMA -array-inner ;\\n\\narray = LBRACKET RBRACKET ;\\narray = LBRACKET -array-inner RBRACKET ;\\n\\ndefn = DEF ID EQ expr ;\\n\\npriorities {\\n  expr = expr EXP expr > expr = expr TIMES expr ;\\n  expr = expr TIMES expr > expr = expr PLUS expr ;\\n}\\n\",\"~:source-type\":\"~:grammar\",\"~:source-path\":\"fuyu.g\",\"~:id\":1},\"~i2\":{\"~:string\":\"PLUS = \\\\+ ;\\nTIMES = \\\\* ;\\nEXP = \\\\^ ;\\nLPAREN = \\\\( ;\\nRPAREN = \\\\) ;\\nLBRACKET = \\\\[ ;\\nRBRACKET = \\\\] ;\\nCOMMA = , ;\\nEQ = = ;\\nDEF = def ;\\nID = [a-zA-Z] [a-zA-Z0-9_]* ;\\nNUM = \\\\-? (0 | [1-9] [0-9]*) (\\\\. [0-9]+)? ([Ee] [+\\\\-]? (0 | [1-9] [0-9]*))? ;\\n\",\"~:source-type\":\"~:token\",\"~:source-path\":\"fuyu.t\",\"~:id\":2},\"~i3\":{\"~:string\":\"def a = 2\\ndef alpha = a\\ndef gamma1 = (a+-88)^(a*0.3)\\ndef Delta_ = [1e12, 6.022e+23, -12.2E-10]\\ndef nested = [\\n  [a, (alpha+1)*(Delta_^alpha)],\\n  [0]\\n]\\n\",\"~:source-type\":\"~:file\",\"~:source-path\":\"sample.fuyu\",\"~:id\":3}},\"~:file-picker-state\":[{\"~:id\":0,\"~:parent\":null,\"~:draggable\":false,\"~:data\":{\"~#file-picker/Heading\":{\"~:id\":0,\"~:fname\":\"Project\",\"~:md-icon-name\":\"zmdi-storage\",\"~:editable?\":false}}},{\"~:id\":1,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":1}}},{\"~:id\":2,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":2}}},{\"~:id\":3,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":3}}}],\"~:token-dashboard\":{\"~:samples\":[{\"~:id\":0,\"~:parent\":null,\"~:draggable\":false,\"~:data\":{\"~#token-dashboard/Heading\":{\"~:id\":0,\"~:label-str\":\"Samples\",\"~:md-icon-name\":\"zmdi-format-list-bulleted\",\"~:editable?\":false,\"~:horizon\":null,\"~:example-strings\":{}}},\"~:selected\":false}]},\"~:parse-dashboard\":{\"~:samples\":[{\"~:id\":0,\"~:parent\":null,\"~:draggable\":false,\"~:data\":{\"~#parse-dashboard/Heading\":{}},\"~:selected\":false}]}}"
  )

(def demo-string
  "{\"~:id\":null,\"~:last-saved\":1499468098964,\"~:description\":\"DEMO\",\"~:sources\":{\"~i1\":{\"~:string\":\"def\\n+\\n*\\n^\\n(\\n)\\n[\\n]\\n,\\n=\\n\",\"~:source-type\":\"~:file\",\"~:source-path\":\"1.tokens\",\"~:id\":1},\"~i2\":{\"~:string\":\"a\\nalpha\\ngamma1\\nDelta_\\nnested\\n\",\"~:source-type\":\"~:file\",\"~:source-path\":\"2.tokens\",\"~:id\":2},\"~i3\":{\"~:string\":\"\",\"~:source-type\":\"~:grammar\",\"~:source-path\":\"fuyu.g\",\"~:id\":3},\"~i4\":{\"~:string\":\"\",\"~:source-type\":\"~:token\",\"~:source-path\":\"fuyu.t\",\"~:id\":4},\"~i5\":{\"~:string\":\"2\\n-88\\n0.3\\n1e12\\n6.0221409e+23\\n-1.2e-10\\n\",\"~:source-type\":\"~:file\",\"~:source-path\":\"3.tokens\",\"~:id\":5},\"~i6\":{\"~:string\":\"PLUS = \\\\+ ;\\nTIMES = \\\\* ;\\nEXP = \\\\^ ;\\nLPAREN = \\\\( ;\\nRPAREN = \\\\) ;\\nLBRACKET = \\\\[ ;\\nRBRACKET = \\\\] ;\\nCOMMA = , ;\\nEQ = = ;\\nDEF = def ;\\nID = [a-zA-Z] [a-zA-Z0-9_]* ;\\nNUM = \\\\-? (0 | [1-9] [0-9]*) (\\\\. [0-9]+)? ([Ee] [+\\\\-]? (0 | [1-9] [0-9]*))? ;\\n\",\"~:source-type\":\"~:file\",\"~:source-path\":\"cheatsheet\",\"~:id\":6},\"~i7\":{\"~:string\":\"def a = 2\\ndef alpha = a\\ndef gamma1 = (a+-88)^(a*0.3)\\ndef Delta_ = [1e12, 6.022e+23, -12.2E-10]\\ndef nested = [\\n  [a, (alpha+1)*(Delta_^alpha)],\\n  [0]\\n]\\n\",\"~:source-type\":\"~:file\",\"~:source-path\":\"sample.fuyu\",\"~:id\":7}},\"~:file-picker-state\":[{\"~:id\":0,\"~:parent\":null,\"~:draggable\":false,\"~:data\":{\"~#file-picker/Heading\":{\"~:id\":0,\"~:fname\":\"Project\",\"~:md-icon-name\":\"zmdi-storage\",\"~:editable?\":false}}},{\"~:id\":3,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":3}}},{\"~:id\":4,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":4}}},{\"~:id\":7,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":7}}},{\"~:id\":1,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":1}}},{\"~:id\":2,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":2}}},{\"~:id\":5,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":5}}},{\"~:id\":6,\"~:parent\":0,\"~:targetable\":false,\"~:data\":{\"~#file-picker/SourceLink\":{\"~:source-id\":6}}}],\"~:token-dashboard\":{\"~:samples\":[{\"~:id\":0,\"~:parent\":null,\"~:draggable\":false,\"~:data\":{\"~#token-dashboard/Heading\":{\"~:id\":0,\"~:label-str\":\"Samples\",\"~:md-icon-name\":\"zmdi-format-list-bulleted\",\"~:editable?\":false,\"~:horizon\":null,\"~:example-strings\":{}}},\"~:selected\":false}]},\"~:parse-dashboard\":{\"~:samples\":[{\"~:id\":0,\"~:parent\":null,\"~:draggable\":false,\"~:data\":{\"~#parse-dashboard/Heading\":{}},\"~:selected\":false}]}}"
  )

